### PR TITLE
Add all required files.

### PR DESCRIPTION
**Pull request by Cisco-the-wayword**
Completed the requirements and ready to merge

### CODE REVIEW

**Comment by Kingstalux** [comment]
Hi @Cisco-the-wayword, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :x: 

- [ ] You have submitted a project, that has been merged and the branch has been deleted. Kindly submit a PR that has not been merged and wait for a review before merging.
- [ ] Also kindly set up your [linters](https://github.com/microverseinc/linters-config) and make sure the checks show up on GitHub and they should be passing :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Cisco-the-wayword** [comment]
Hey @Kingstalux,
Do I delete the merged files from the former pull request and then try it again or do I make new files without performing any actions on the ones already there?

**Comment by Kingstalux** [comment]
> Hey @Kingstalux, Do I delete the merged files from the former pull request and then try it again or do I make new files without performing any actions on the ones already there?

Hello @Cisco-the-wayword, to avoid any confusion, just create a new repo, then create your `feature-branch` and copy your code and paste there. Then open your Pull request but do not merge it. You can now ask for a review then.

**Comment by Kingstalux** [comment]
Also, do not forget to set up your linters and make sure that the linters checks are showing up on Github :+1:

**Comment by Cisco-the-wayword** [comment]
Okay. Thank you @Kingstalux

**Pull request merged**
